import Foundation
import Supabase

// MARK: - VehicleInspectionInsert
// Explicit insert struct — excludes created_at (auto-generated by DB).
private struct VehicleInspectionInsert: Encodable {
    let id: UUID
    let vehicle_id: UUID
    let driver_id: UUID?
    let trip_id: UUID?
    let inspection_type: InspectionType?
    let notes: String?
}

enum InspectionService {

    static func fetchAllInspections() async throws -> [VehicleInspection] {
        do {
            let result: [VehicleInspection] = try await supabase
                .from("vehicle_inspections")
                .select()
                .execute()
                .value
            print("[InspectionService] fetchAllInspections: \(result.count) records")
            return result
        } catch {
            print("[InspectionService] fetchAllInspections ERROR: \(error)")
            throw error
        }
    }

    static func fetchInspections(vehicleId: UUID) async throws -> [VehicleInspection] {
        do {
            let result: [VehicleInspection] = try await supabase
                .from("vehicle_inspections")
                .select()
                .eq("vehicle_id", value: vehicleId)
                .execute()
                .value
            print("[InspectionService] fetchInspections(vehicleId=\(vehicleId)): \(result.count)")
            return result
        } catch {
            print("[InspectionService] fetchInspections(vehicleId=\(vehicleId)) ERROR: \(error)")
            throw error
        }
    }

    static func fetchInspectionsForDriver(driverId: UUID) async throws -> [VehicleInspection] {
        do {
            let result: [VehicleInspection] = try await supabase
                .from("vehicle_inspections")
                .select()
                .eq("driver_id", value: driverId)
                .execute()
                .value
            print("[InspectionService] fetchInspectionsForDriver(\(driverId)): \(result.count)")
            return result
        } catch {
            print("[InspectionService] fetchInspectionsForDriver(\(driverId)) ERROR: \(error)")
            throw error
        }
    }

    static func createInspection(_ inspection: VehicleInspection) async throws {
        let payload = VehicleInspectionInsert(
            id: inspection.id,
            vehicle_id: inspection.vehicleId,
            driver_id: inspection.driverId,
            trip_id: inspection.tripId,
            inspection_type: inspection.inspectionType,
            notes: inspection.notes
        )
        do {
            try await supabase
                .from("vehicle_inspections")
                .insert(payload)
                .execute()
            print("[InspectionService] createInspection(\(inspection.id)) type=\(inspection.inspectionType?.rawValue ?? "?"): OK")
        } catch {
            print("[InspectionService] createInspection ERROR: \(error)")
            throw error
        }
    }

    static func createInspectionPhoto(_ photo: InspectionPhoto) async throws {
        do {
            try await supabase
                .from("inspection_photos")
                .insert(photo)
                .execute()
            print("[InspectionService] createInspectionPhoto(\(photo.id)): OK")
        } catch {
            print("[InspectionService] createInspectionPhoto ERROR: \(error)")
            throw error
        }
    }
}
