import Foundation
import Supabase

// MARK: - NotificationInsert
// Explicit insert struct — excludes created_at (auto-generated by DB).
private struct NotificationInsert: Encodable {
    let id: UUID
    let user_id: UUID
    let title: String?
    let message: String?
    let type: NotificationType?
    let is_read: Bool
    let reference_id: UUID?
}

enum NotificationService {

    static func fetchNotifications(userId: UUID) async throws -> [Notification] {
        do {
            let result: [Notification] = try await supabase
                .from("notifications")
                .select()
                .eq("user_id", value: userId)
                .order("created_at", ascending: false)
                .execute()
                .value
            print("[NotificationService] fetchNotifications(\(userId)): \(result.count) notifications")
            return result
        } catch {
            print("[NotificationService] fetchNotifications(\(userId)) ERROR: \(error)")
            throw error
        }
    }

    static func createNotification(_ notification: Notification) async throws {
        // Use explicit insert to avoid sending created_at if it conflicts with DB default
        let payload = NotificationInsert(
            id: notification.id,
            user_id: notification.userId,
            title: notification.title,
            message: notification.message,
            type: notification.type,
            is_read: notification.isRead,
            reference_id: notification.referenceId
        )
        do {
            try await supabase
                .from("notifications")
                .insert(payload)
                .execute()
            print("[NotificationService] createNotification for userId=\(notification.userId): OK")
        } catch {
            print("[NotificationService] createNotification ERROR: \(error)")
            throw error
        }
    }

    /// Notifies the specific fleet manager associated with a vehicle
    static func notifyManager(forVehicle vehicleId: UUID, title: String, message: String, type: NotificationType, referenceId: UUID? = nil) async throws {
        if let vehicle = try? await VehicleService.fetchVehicle(id: vehicleId), let adminId = vehicle.adminId {
            let notification = Notification(
                id: UUID(),
                userId: adminId,
                title: title,
                message: message,
                type: type,
                isRead: false,
                referenceId: referenceId,
                createdAt: Date()
            )
            try await createNotification(notification)
        }
    }

    /// Notifies the specific fleet manager associated with a trip's vehicle
    static func notifyManager(forTrip tripId: UUID, title: String, message: String, type: NotificationType, referenceId: UUID? = nil) async throws {
        if let trip = try? await TripService.fetchTrip(id: tripId) {
            try await notifyManager(forVehicle: trip.vehicleId, title: title, message: message, type: type, referenceId: referenceId)
        }
    }

    static func markAsRead(id: UUID) async throws {
        struct ReadUpdate: Encodable {
            let is_read: Bool
        }
        do {
            try await supabase
                .from("notifications")
                .update(ReadUpdate(is_read: true))
                .eq("id", value: id)
                .execute()
            print("[NotificationService] markAsRead(\(id)): OK")
        } catch {
            print("[NotificationService] markAsRead(\(id)) ERROR: \(error)")
            throw error
        }
    }

    static func deleteNotifications(forReferenceId referenceId: UUID) async throws {
        do {
            try await supabase
                .from("notifications")
                .delete()
                .eq("reference_id", value: referenceId)
                .execute()
            print("[NotificationService] deleteNotifications(referenceId:\(referenceId)): OK")
        }
    }

    static func deleteNotification(id: UUID) async throws {
        do {
            try await supabase
                .from("notifications")
                .delete()
                .eq("id", value: id)
                .execute()
            print("[NotificationService] deleteNotification(id:\(id)): OK")
        } catch {
            print("[NotificationService] deleteNotification ERROR: \(error)")
            throw error
        }
    }
}