import Foundation
import Supabase

// MARK: - WorkOrderInsert
// Explicit insert struct — excludes created_at (DB generates it) to avoid conflict.
private struct WorkOrderInsert: Encodable {
    let id: UUID
    let vehicle_id: UUID
    let created_by: UUID?
    let assigned_to: UUID?
    let priority: WorkOrderPriority?
    let status: WorkOrderStatus?
}

enum WorkOrderService {

    static func fetchAllWorkOrders() async throws -> [WorkOrder] {
        do {
            let result: [WorkOrder] = try await supabase
                .from("work_orders")
                .select()
                .execute()
                .value
            print("[WorkOrderService] fetchAllWorkOrders: \(result.count) records")
            return result
        } catch {
            print("[WorkOrderService] fetchAllWorkOrders ERROR: \(error)")
            throw error
        }
    }

    static func fetchWorkOrdersForUser(assignedTo: UUID) async throws -> [WorkOrder] {
        do {
            let result: [WorkOrder] = try await supabase
                .from("work_orders")
                .select()
                .eq("assigned_to", value: assignedTo)
                .execute()
                .value
            print("[WorkOrderService] fetchWorkOrdersForUser(\(assignedTo)): \(result.count) records")
            return result
        } catch {
            print("[WorkOrderService] fetchWorkOrdersForUser(\(assignedTo)) ERROR: \(error)")
            throw error
        }
    }

    /// Safe insert — does not send created_at (auto-generated by DB).
    static func createWorkOrder(vehicleId: UUID, createdBy: UUID?, assignedTo: UUID?, priority: WorkOrderPriority?, status: WorkOrderStatus?) async throws -> UUID {
        let newId = UUID()
        let payload = WorkOrderInsert(
            id: newId,
            vehicle_id: vehicleId,
            created_by: createdBy,
            assigned_to: assignedTo,
            priority: priority,
            status: status
        )
        do {
            try await supabase
                .from("work_orders")
                .insert(payload)
                .execute()
            print("[WorkOrderService] createWorkOrder: OK id=\(newId)")
            return newId
        } catch {
            print("[WorkOrderService] createWorkOrder ERROR: \(error)")
            throw error
        }
    }

    static func updateWorkOrder(_ workOrder: WorkOrder) async throws {
        do {
            try await supabase
                .from("work_orders")
                .update(workOrder)
                .eq("id", value: workOrder.id)
                .execute()
            print("[WorkOrderService] updateWorkOrder(\(workOrder.id)): OK")
        } catch {
            print("[WorkOrderService] updateWorkOrder(\(workOrder.id)) ERROR: \(error)")
            throw error
        }
    }

    static func updateWorkOrderStatus(id: UUID, status: WorkOrderStatus) async throws {
        struct StatusUpdate: Encodable {
            let status: WorkOrderStatus
        }
        do {
            try await supabase
                .from("work_orders")
                .update(StatusUpdate(status: status))
                .eq("id", value: id)
                .execute()
            print("[WorkOrderService] updateWorkOrderStatus(\(id)) → \(status.rawValue): OK")
        } catch {
            print("[WorkOrderService] updateWorkOrderStatus(\(id)) ERROR: \(error)")
            throw error
        }
    }
}