import Foundation
import Supabase

// MARK: - WorkOrderInsert
// Explicit insert — excludes created_at (DB auto-generates) and lifecycle_status
// (let DB apply its default status on creation).
private struct WorkOrderInsert: Encodable {
    let id: UUID
    let vehicle_id: UUID
    let created_by: UUID?
    let assigned_to: UUID?
    let priority: WorkOrderPriority?
}

enum WorkOrderService {

    static func fetchAllWorkOrders() async throws -> [WorkOrder] {
        do {
            let result: [WorkOrder] = try await supabase
                .from("work_orders")
                .select()
                .execute()
                .value
            print("[WorkOrderService] fetchAllWorkOrders: \(result.count) records")
            return result
        } catch {
            print("[WorkOrderService] fetchAllWorkOrders ERROR: \(error)")
            throw error
        }
    }

    static func fetchWorkOrdersForUser(assignedTo: UUID) async throws -> [WorkOrder] {
        do {
            let result: [WorkOrder] = try await supabase
                .from("work_orders")
                .select()
                .eq("assigned_to", value: assignedTo)
                .execute()
                .value
            print("[WorkOrderService] fetchWorkOrdersForUser(\(assignedTo)): \(result.count) records")
            return result
        } catch {
            print("[WorkOrderService] fetchWorkOrdersForUser(\(assignedTo)) ERROR: \(error)")
            throw error
        }
    }

    /// Safe insert — does not send created_at (auto-generated by DB).
    static func createWorkOrder(vehicleId: UUID, createdBy: UUID?, assignedTo: UUID?, priority: WorkOrderPriority?, status: WorkOrderStatus?) async throws -> UUID {
        let newId = UUID()
        let payload = WorkOrderInsert(
            id: newId,
            vehicle_id: vehicleId,
            created_by: createdBy,
            assigned_to: assignedTo,
            priority: priority == .critical ? .high : priority
            // status intentionally omitted — DB uses its lifecycle_status default
        )
        do {
            try await supabase
                .from("work_orders")
                .insert(payload)
                .execute()
            print("[WorkOrderService] createWorkOrder: OK id=\(newId)")
            return newId
        } catch {
            print("[WorkOrderService] createWorkOrder ERROR: \(error)")
            throw error
        }
    }

    // Safe update — only writes columns confirmed in the DB schema.
    // Excludes 'status' because the DB column is lifecycle_status with unknown enum values.
    static func updateWorkOrder(_ workOrder: WorkOrder) async throws {
        struct WorkOrderUpdate: Encodable {
            let vehicle_id: UUID
            let created_by: UUID?
            let assigned_to: UUID?
            let priority: WorkOrderPriority?
        }
        let priority: WorkOrderPriority? = workOrder.priority == .critical ? .high : workOrder.priority
        let payload = WorkOrderUpdate(
            vehicle_id: workOrder.vehicleId,
            created_by: workOrder.createdBy,
            assigned_to: workOrder.assignedTo,
            priority: priority
        )
        do {
            try await supabase
                .from("work_orders")
                .update(payload)
                .eq("id", value: workOrder.id)
                .execute()
            print("[WorkOrderService] updateWorkOrder(\(workOrder.id)): OK")
        } catch {
            print("[WorkOrderService] updateWorkOrder(\(workOrder.id)) ERROR: \(error)")
            throw error
        }
    }

    // Updating just the assigned_to field is safe (no enum involved).
    static func reassignWorkOrder(id: UUID, assignedTo: UUID?) async throws {
        struct AssignUpdate: Encodable {
            let assigned_to: UUID?
        }
        do {
            try await supabase
                .from("work_orders")
                .update(AssignUpdate(assigned_to: assignedTo))
                .eq("id", value: id)
                .execute()
            print("[WorkOrderService] reassignWorkOrder(\(id)): OK")
        } catch {
            print("[WorkOrderService] reassignWorkOrder(\(id)) ERROR: \(error)")
            throw error
        }
    }

    // NOTE: updateWorkOrderStatus is intentionally a no-op — the DB work_orders table uses
    // a 'lifecycle_status' enum column whose valid values don't match WorkOrderStatus.
    // Until the DB enum values are confirmed, this silently skips the write to avoid errors.
    static func updateWorkOrderStatus(id: UUID, status: WorkOrderStatus) async throws {
        print("[WorkOrderService] updateWorkOrderStatus: skipped — lifecycle_status enum mismatch. id=\(id) status=\(status.rawValue)")
    }
}