import Foundation
import Supabase
import SwiftUI
import Observation



@MainActor
@Observable
class AuthViewModel {
    var isAuthenticated = false
    var currentUser: Auth.User?
    var errorMessage: String?
    var isLoading = false
    var isSessionChecked = false
    
    var userRole: String? {
        guard let metadata = currentUser?.userMetadata,
              let roleJSON = metadata["role"],
              case .string(let role) = roleJSON else {
            return nil
        }
        return role
    }
    
    func checkUserSession() async {
        do {
            let session = try await supabase.auth.session
            self.currentUser = session.user
            self.isAuthenticated = true
        } catch {
            self.isAuthenticated = false
            self.currentUser = nil
        }
        self.isSessionChecked = true
    }
    
    // Only Fleet Managers are allowed to sign up. Drivers and maintenance are generated by the admin.
    func signUp(email: String, password: String, fullName: String) async {
        isLoading = true
        errorMessage = nil
        do {
            let metadata: [String: AnyJSON] = [
                "fullName": .string(fullName),
                "role": .string("fleet_manager")
            ]
            let response = try await supabase.auth.signUp(
                email: email,
                password: password,
                data: metadata
            )
            self.currentUser = response.user
            self.isAuthenticated = true
        } catch {
            self.errorMessage = error.localizedDescription
        }
        isLoading = false
    }
    
    func signIn(email: String, password: String) async {
        isLoading = true
        errorMessage = nil
        do {
            let response = try await supabase.auth.signIn(email: email, password: password)
            self.currentUser = response.user
            self.isAuthenticated = true
        } catch {
            self.errorMessage = error.localizedDescription
        }
        isLoading = false
    }
    
    func signOut() async {
        do {
            try await supabase.auth.signOut()
            self.isAuthenticated = false
            self.currentUser = nil
        } catch {
            self.errorMessage = error.localizedDescription
        }
    }
}
